### ISSUE TITLE
Export list of market items with price and quantity for CSV

### ISSUE THREAD

**Issue by YuudaiNoboru** [levelnineteen/tos#1]
Hello and congratulations for the great work with the addons. Would it be possible to make the Inventory CSV addon besides exporting the inventory also export the store items, such as name and price? This would be very useful for people like me who live selling items in the market. We could more easily manage the prices of the market in excel, putting filters and etc, besides being able to compare directly the prices of the market plan with the plan of the inventory. Could this be done? Thank you very much.

**Comment by levelnineteen** [comment]
そのあたりはwritさんのMarket Historyをつかってください。マーケットのアイテムを直接取る方法があれば別ですが、今のところその方法はないので。
